### ISSUE TITLE
Multiple subreddits

### ISSUE THREAD

**Issue by Esionru** [renoki-co/reddit-json-api#9]
Hello! How can I fetch data from multiple subreddits?

**Comment by rennokki** [comment]
Just create multiple instances like in the following example:

```php
$subreddits = ['funny', 'dankmemes', 'tifu'];

foreach ($subreddits as $subreddit) {
    $posts = Reddit::subreddit($subreddit, $app)->get();

    //
}
```

**Comment by kgnfth** [comment]
How to shuffle ?
i tried $posts->shuffle() but it does not work 😭

**Comment by rennokki** [comment]
```php
foreach ($posts->shuffle() as $post) {
    //
}
```

**Comment by kgnfth** [comment]
> ```
> $subreddits = ['funny', 'dankmemes', 'tifu'];
> ```

i am trying to shuffle `$subreddits = ['funny', 'dankmemes', 'tifu'];` so that i have randomized list instead of the list of the orders defined in the array

so  `$posts = Reddit::subreddit($subreddit, $app)->get();` gets the list by order
